#!/usr/bin/env node
/**
 * Google Cookies Extractor for google-ai-mode-mcp
 * 
 * This script opens a visible browser, lets you log in to Google,
 * and extracts the authentication cookies needed for CAPTCHA-free operation.
 * 
 * Usage:
 *   node scripts/extract-cookies.js
 * 
 * Output:
 *   Creates/updates .env file with GOOGLE_AI_COOKIES variable
 */

import { chromium } from 'patchright';
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import readline from 'readline';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT_DIR = path.resolve(__dirname, '..');
const ENV_FILE = path.join(ROOT_DIR, '.env');

// Google auth cookie names
const GOOGLE_COOKIE_NAMES = [
  'AEC', 'SIDCC', 'SID', 'HSID', 'SSID', 'APISID', 'SAPISID',
  '1P_JAR', 'NID', 'CONSENT', 'SOCS', 'OSID', 'SIDPS', 'RPLC',
  '__Secure-1PSID', '__Secure-1PSIDCC', '__Secure-3PSID', '__Secure-3PSIDCC'
];

function createReadlineInterface() {
  return readline.createInterface({
    input: process.stdin,
    output: process.stdout
  });
}

function askQuestion(rl, question) {
  return new Promise((resolve) => {
    rl.question(question, (answer) => {
      resolve(answer);
    });
  });
}

function formatCookiesAsJson(cookies) {
  const googleCookies = {};
  for (const cookie of cookies) {
    if (GOOGLE_COOKIE_NAMES.some(name => 
      cookie.name.toLowerCase().includes(name.toLowerCase())
    )) {
      googleCookies[cookie.name] = cookie.value;
    }
  }
  return googleCookies;
}

function formatCookiesAsEnv(cookies) {
  const parts = [];
  for (const [name, value] of Object.entries(cookies)) {
    parts.push(`${name}=${value}`);
  }
  return parts.join('; ');
}

function saveCookiesToEnv(cookies) {
  const cookiesJson = JSON.stringify(cookies);
  const cookiesEnv = formatCookiesAsEnv(cookies);
  
  let envContent = '';
  if (fs.existsSync(ENV_FILE)) {
    envContent = fs.readFileSync(ENV_FILE, 'utf-8');
  }
  
  // Check if GOOGLE_AI_COOKIES already exists
  const cookiesRegex = /^GOOGLE_AI_COOKIES=.*$/m;
  if (cookiesRegex.test(envContent)) {
    // Replace existing
    envContent = envContent.replace(cookiesRegex, `GOOGLE_AI_COOKIES=${cookiesEnv}`);
  } else {
    // Add new
    const authSection = `
# =============================================================================
# AUTHENTICATION (Auto-generated by extract-cookies.js)
# =============================================================================
GOOGLE_AI_COOKIES=${cookiesEnv}
`;
    envContent += authSection;
  }
  
  fs.writeFileSync(ENV_FILE, envContent, 'utf-8');
  console.log(`\n✅ Cookies saved to ${ENV_FILE}`);
  console.log(`\n📋 JSON format (for reference):`);
  console.log(JSON.stringify(cookies, null, 2));
}

async function main() {
  const rl = createReadlineInterface();
  
  console.log('🍪 Google Cookies Extractor for google-ai-mode-mcp\n');
  console.log('This script will:');
  console.log('1. Open a Chrome browser');
  console.log('2. Navigate to Google AI Search');
  console.log('3. Let you log in and solve any CAPTCHA');
  console.log('4. Extract authentication cookies');
  console.log('5. Save them to .env file\n');
  
  await askQuestion(rl, 'Press Enter to open the browser...');
  
  let browser;
  try {
    console.log('🚀 Launching browser...');
    browser = await chromium.launch({
      channel: 'chrome',
      headless: false,
      args: [
        '--disable-blink-features=AutomationControlled',
        '--disable-dev-shm-usage',
        '--no-sandbox',
      ]
    });
    
    const context = await browser.newContext({
      userAgent: 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36',
      locale: 'en-US',
      viewport: { width: 1920, height: 1080 }
    });
    
    const page = await context.newPage();
    
    console.log('📍 Navigating to Google AI Search...');
    await page.goto('https://www.google.com/search?udm=50&q=authentication+test', {
      waitUntil: 'domcontentloaded'
    });
    
    console.log('\n👉 INSTRUCTIONS:');
    console.log('   1. If you see a CAPTCHA, please solve it');
    console.log('   2. Make sure you are logged in to your Google account');
    console.log('   3. Wait for the search results to load');
    console.log('   4. You should see AI-generated search results\n');
    
    await askQuestion(rl, 'Press Enter when you see the Google AI search results page...');
    
    // Extract cookies
    console.log('🍪 Extracting cookies...');
    const cookies = await context.cookies();
    const googleCookies = formatCookiesAsJson(cookies);
    
    if (Object.keys(googleCookies).length === 0) {
      console.log('\n⚠️  No Google authentication cookies found!');
      console.log('   Please make sure you are logged in to Google.');
    } else {
      console.log(`\n✅ Found ${Object.keys(googleCookies).length} Google authentication cookies:`);
      for (const name of Object.keys(googleCookies)) {
        console.log(`   - ${name}`);
      }
      
      saveCookiesToEnv(googleCookies);
      
      console.log('\n✅ Done! You can now use google-ai-mode-mcp without CAPTCHA.');
      console.log('   The cookies will be automatically loaded from .env file.');
    }
    
  } catch (error) {
    console.error('\n❌ Error:', error.message);
  } finally {
    if (browser) {
      await browser.close();
    }
    rl.close();
  }
}

main().catch(console.error);
